### ISSUE TITLE
[Chore] 기능 수정

### ISSUE THREAD

**Issue by lee-youn** [Kaggom/Kaggom_FE#21]
## 내용
기존 기능들을 수정합니다.

- 해당 공지로 이동할 때 새창 띄우기
- 온보딩에 복수전공, 부전공 추가하기
- 채팅 엔터 치면 보내지게 하기 구현
- 사이드바 렌더링 수정
- 이전기록 클릭하면 채팅으로 이동 구현

## 작업내용
- [ ] Kaggom/Kaggom_FE/issues/22
- [ ] Kaggom/Kaggom_FE/issues/23
- [ ] Kaggom/Kaggom_FE/issues/24
- [ ] Kaggom/Kaggom_FE/issues/25
- [ ] Kaggom/Kaggom_FE/issues/26
